<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Avila.Bridge\Avila.Bridge.csproj" />
    <ProjectReference Include="..\Avila.Security\Avila.Security.csproj" />
  </ItemGroup>
</Project>
